version: '3'


services:

  manager-db:
      container_name: manager-db
      restart: always
      image: mysql:5.7
      ports:
        - 3307:3306
      expose:
        - 3306
      networks:
        - manager-network
        - services
      volumes:
        - manager-db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password


  manager-ms:
      image: jboss/keycloak
      container_name: manager-ms
      networks:
        - manager-network
        - services

      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: manager-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 3003:8080
      depends_on:
        - manager-db

volumes:
  manager-db:
      driver: local

networks:
  manager-network:
    driver: 'bridge'
  services:
    external: true
    driver: 'bridge'